server:
  port : 8085
spring:
  datasource:
    url:  jdbc:h2:mem:db
    username: sa
    password:
    driverClassName: org.h2.Driver

  jpa:
    defer-datasource-initialization: false

  h2:
    console:
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: true

  liquibase:
    changeLog: classpath:db/changelog/db.changelog-master.yaml

app:
  jwt:
    secret: abcdefghijklmnOPQRSTUVWXYZ