server:
  port : 8085
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

spring:
  datasource:
    url:  jdbc:h2:mem:db
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
    defer-datasource-initialization: false

  h2:
    console:
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: true

  liquibase:
    changeLog: classpath:db/changelog/db.changelog-master.yaml

app:
  jwt:
    secret: abcdefghijklmnOPQRSTUVWXYZ
    validity: 86400000
    authorities: roles
    header:  Authorization
    prefix:  Bearer
